base_url = "https://dennis-das.github.io"
title = "Abhisek Das"
description = "Senior Backend Engineer | Curiosity-led. Tinkerer-minded. Forever learning."
theme = "apollo"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
smart_punctuation = true

[extra]
toc = true
use_cdn = false
theme = "toggle"
fancy_code = true
dynamic_note = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/dennis-das", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/das-abhisek/", icon = "linkedin" },
    { name = "email", url = "mailto:abhisekcosmos82@gmail.com", icon = "email" },
]

stylesheets = []

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[extra.analytics]
enabled = false
